export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_ROLE = 'USER_ROLE'